# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d45474033212b737b5330f0e79e6013cfffb8ab713035c40fffe162615658aa40b71e4f9255117fd90b1a175bc8a9100f872dc9be90a6df2e2ac8d494eb47e8

test:
  secret_key_base: feff9d71a9cbd04db2c6478c9e21c14aef2f6e90d2a95d6508605a3e488834f45c989c010a84db0ec3729c9e392eb472744d96f3cbe9e2c4a9358ce95f3acb6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
